# Netlify Configuration for MyPA Notes PWA
[build]
  publish = "dist"
  command = "npm run build"

# Environment Variables
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Headers for Security and PWA
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    
    # PWA Headers
    Cache-Control = "public, max-age=86400"

# Service Worker and PWA files
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
    Service-Worker-Allowed = "/"

[[headers]]
  for = "/workbox-*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

# Static Assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# SPA Routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Redirects
[[redirects]]
  from = "http://mypa.netlify.app/*"
  to = "https://mypa.netlify.app/:splat"
  status = 301
  force = true

# Error Pages
[[redirects]]
  from = "/404"
  to = "/index.html"
  status = 200